baseurl: "/hpcu"
collections_dir: "collections"
collections:
  resources:
    output: true
    permalink: "/resources/:path/view/"
  single-pages:
    output: true
    permalink: "/:path/"
  training-materials:
    output: true
    permalink: "/trainingMaterials/:path/"
defaults:
  - scope:
      type: "resources"
    values:
      layout: "resource"
  - scope:
      type: "single-pages"
    values:
      layout: "default"
  - scope:
      type: "training-materials"
    values:
      layout: "training-materials"
exclude:
  - "exclude"
gray: "#f0f0f0"
# During dev, uncomment dirs below you don't need to generate — speeds up build
#  - "_resources"
plugins:
  - "jekyll-redirect-from"
sass:
  style: "compressed"
url: "https://shodor-education.github.io"
whitelist:
  - "jekyll-redirect-from"
